name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        env:
          RPY2_CFFI_MODE: ABI
        run: |
          python -m pip install --upgrade pip
          pip install -r site/requirements.txt

      - name: Build the book
        run: |
          jupyter-book toc from-project site -e .md -e .ipynb -i about > site/_toc.yml
          jupyter-book build site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/_build/html
          cname: chrismathy.com
